services:
  dns:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns_reto6
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf:ro
      - ./bind/for.daw.lan:/etc/bind/for.daw.lan:ro
      - ./bind/rev.daw.lan:/etc/bind/rev.daw.lan:ro
    restart: unless-stopped

  reto6_web_2:
    image: nginx:alpine
    container_name: reto6_web_2
    ports:
      - "8080:80"
    volumes:
      - /Users/juancaravantes/Documents/GitHub/DDAW-DAW/DNS/reto6-dns/frontend:/usr/share/nginx/html:ro
    restart: unless-stopped