options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query { any; };
    forwarders {
        8.8.8.8;
    };
};

zone "daw.lan" {
    type master;
    file "/etc/bind/for.daw.lan";
};

zone "1.0.0.127.in-addr.arpa" {
    type master;
    file "/etc/bind/rev.daw.lan";
};

